import Head from "next/head";
import axios from "axios";
import AOS from "aos";
import "aos/dist/aos.css";

import BrandStory from "../components/page/BrandStory";
import WorkSection from "../components/page/WorkSection";
import Spotlight from "../components/page/Spotlight";
import News from "../components/page/News";
import Network from "../components/page/Network";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import ContactForm from "../components/layout/ContactForm";
import Locations from "../components/layout/Locations";
import SecondFooter from "../components/layout/SecondFooter";
import SecondNavbar from "../components/layout/SecondNavbar";
import { useEffect } from "react";

export default function Home({
  sliderItems,
  homepageInfo,
  teamMembers,
  aboutInfo,
  workItems,
  workCategories,
  instaToken,
}) {
  useEffect(() => {
    axios
      .post("https://api.instagram.com/oauth/access_token", {
        auth: {
          client_id: "482350026570502",
          client_secret: "4dc533f88136132b623782bf40c183a9",
          grant_type: "authorization_code",
          redirect_uri:
            "https://aja-adk-frontend-git-development-aimtechllc.vercel.app/",
          code: "AQB9FWK_ARL6U08TkyFRnRoQm9LuqQaedLan6T2M6OrZvTmS76SLO028TFUIwzg54HJeivf1W3suKVACl0YX5uSfnsjrS3IiZJE-7HITRYjICOYKef4gzgBwTynDyrIVlIWdg6KUjRmBNRGotnHCJrzLynhy1nyyT7tz5aVobaqi3p--B1uvYhvzvBa36ejPKH6hm09epA1ZaEJDSkieSdRm3-D_xQ_QaVl22U8Ttv0tdw#_",
        },
      })
      .then((response) => {
        console.log("response insta token", response);
      });
  }, []);
  console.log("instaToken", instaToken);
  return (
    <>
      <Header sliderItems={sliderItems} />
      <div>
        <Head>
          <title>AGA ADK</title>
          <meta name="description" content="Generated by create next app " />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <BrandStory homepage={true} info={aboutInfo} />
          <WorkSection workItems={workItems} workCategories={workCategories} />
          <Spotlight members={teamMembers} />
          <News />
          <Network />
        </main>
      </div>
      <div className="hidden md:block">
        <Footer />
        <ContactForm />
      </div>
      <div className="block md:hidden ">
        <Locations />
        <Footer />
        <SecondFooter />
      </div>
    </>
  );
}

export async function getStaticProps() {
  try {
    const res = await Promise.all([
      axios.get(
        `${process.env.NEXT_PUBLIC_BACKEND}${process.env.NEXT_PUBLIC_HOME_SLIDER}`
      ),
      axios.get(
        `${process.env.NEXT_PUBLIC_BACKEND}${process.env.NEXT_PUBLIC_HOME_INFO}`
      ),
      axios.get(
        `${process.env.NEXT_PUBLIC_BACKEND}${process.env.NEXT_PUBLIC_HOME_TEAM}`
      ),
      axios.get(
        `${process.env.NEXT_PUBLIC_BACKEND}${process.env.NEXT_PUBLIC_ABOUT_INFO}`
      ),
      axios.get(
        `${process.env.NEXT_PUBLIC_BACKEND}${process.env.NEXT_PUBLIC_WORK_WORK}`
      ),
      axios.get(
        `${process.env.NEXT_PUBLIC_BACKEND}${process.env.NEXT_PUBLIC_WORK_CATEGORIES}`
      ),
      // axios.post("https://api.instagram.com/oauth/access_token", {
      //   auth: {
      //     client_id: "482350026570502",
      //     client_secret: "4dc533f88136132b623782bf40c183a9",
      //     grant_type: "authorization_code",
      //     redirect_uri:
      //       "https://aja-adk-frontend-git-development-aimtechllc.vercel.app/",
      //     code: "AQB9FWK_ARL6U08TkyFRnRoQm9LuqQaedLan6T2M6OrZvTmS76SLO028TFUIwzg54HJeivf1W3suKVACl0YX5uSfnsjrS3IiZJE-7HITRYjICOYKef4gzgBwTynDyrIVlIWdg6KUjRmBNRGotnHCJrzLynhy1nyyT7tz5aVobaqi3p--B1uvYhvzvBa36ejPKH6hm09epA1ZaEJDSkieSdRm3-D_xQ_QaVl22U8Ttv0tdw#_",
      //   },
      // }),
    ]);

    const data = res.map((res) => res.data);
    const sliderItems = data[0].items;
    const homepageInfo = data[1].items;
    const teamMembers = data[2].items;
    const aboutInfo = data[3].items;
    const workItems = data[4].items.data;
    const workCategories = data[5].items.data;
    // const instaToken = res[6].access_token;

    return {
      props: {
        sliderItems,
        homepageInfo,
        teamMembers,
        aboutInfo,
        workItems,
        workCategories,
        // instaToken,
      },
      revalidate: 1,
    };
  } catch (error) {
    console.log(error);
  }
}
